"use client";

import type { CreateInvoiceRequest } from "@spaceinvoices/js-sdk";
import { advanceInvoices, creditNotes, deliveryNotes, estimates, invoices } from "@spaceinvoices/js-sdk";
import { Loader2 } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { cn } from "@/ui/lib/utils";
import { useEntities } from "@/ui/providers/entities-context";
import { DocumentPreviewSkeleton } from "../shared/document-preview-skeleton";
import { ScaledDocumentPreview } from "../shared/scaled-document-preview";
import { useA4Scaling } from "../shared/use-a4-scaling";
import type { DocumentTypes } from "../types";
import { filterUnresolvedTaxes, normalizeDocumentPreviewDates } from "./prepare-preview-data";

const LIVE_PREVIEW_TIMING_EVENT = "si:live-preview-timing";
const LIVE_PREVIEW_DEBOUNCE_MS = 300;

function emitLivePreviewDebug(detail: Record<string, unknown>) {
  if (!import.meta.env.DEV || typeof window === "undefined") return;
  window.dispatchEvent(new CustomEvent(LIVE_PREVIEW_TIMING_EVENT, { detail }));
}

export type PdfTemplateId = "modern" | "classic" | "condensed" | "minimal" | "fashion";

type LiveInvoicePreviewProps = {
  data: Partial<CreateInvoiceRequest>;
  currency?: string;
  template?: PdfTemplateId;
  className?: string;
  apiBaseUrl?: string;
  getAuthToken?: () => string | undefined;
  /** Fixed scale to use instead of dynamic scaling. Useful to prevent layout shifts. */
  fixedScale?: number;
  /** Translation function for UI strings */
  t?: (key: string) => string;
  /** Document type label for display (e.g., "Invoice", "Estimate") */
  documentTypeLabel?: string;
  /** Document type to determine which render endpoint to use */
  documentType?: DocumentTypes;
  /** Skip debounce for the first non-empty preview request. */
  eagerFirstPreview?: boolean;
  /** QR settings overrides for preview (before saving) */
  qrOverrides?: {
    upn_qr_enabled?: boolean;
    upn_qr_display_mode?: "qr_only" | "full_slip";
    epc_qr_enabled?: boolean;
  };
};

/**
 * Live Invoice Preview Component
 *
 * Generates a real-time HTML preview of an invoice as the user fills out the form.
 * Uses debouncing to avoid excessive API calls and shows loading states.
 *
 * Features:
 * - Debounced API requests (300ms delay after user stops typing)
 * - Loading skeleton while fetching preview
 * - Error handling with fallback display
 * - Fully styled HTML with scoped CSS (prevents style leakage)
 */
export function LiveInvoicePreview({
  data,
  currency: _currency = "EUR",
  template,
  className,
  fixedScale,
  t: tProp,
  documentTypeLabel: _documentTypeLabel,
  documentType = "invoice",
  eagerFirstPreview = false,
  qrOverrides,
}: LiveInvoicePreviewProps) {
  const t = tProp ?? ((key: string) => key);
  const [previewHtml, setPreviewHtml] = useState<string>("");
  const [isLoading, setIsLoading] = useState(false);
  const [isRefreshPending, setIsRefreshPending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const { activeEntity } = useEntities();
  const abortControllerRef = useRef<AbortController | null>(null);
  const debounceTimeoutRef = useRef<NodeJS.Timeout | null>(null);
  const lastRequestKeyRef = useRef<string | null>(null);
  const hasDispatchedFirstPreviewRef = useRef(false);

  const { containerRef, scale: dynamicScale, A4_WIDTH_PX } = useA4Scaling(previewHtml);
  const scale = fixedScale ?? dynamicScale;

  /**
   * Fetch preview from API
   */
  const fetchPreview = useCallback(
    async (invoiceData: Partial<CreateInvoiceRequest>) => {
      // Don't fetch if no items exist (name can be empty for preview)
      if (!invoiceData.items || invoiceData.items.length === 0) {
        setPreviewHtml("");
        lastRequestKeyRef.current = null;
        setIsRefreshPending(false);
        emitLivePreviewDebug({
          stage: "skipped",
          reason: "no_items",
          documentType,
          itemCount: 0,
        });
        return;
      }

      // Cancel any pending request
      if (abortControllerRef.current) {
        abortControllerRef.current.abort();
      }

      // Create new abort controller for this request
      const abortController = new AbortController();
      abortControllerRef.current = abortController;

      setIsLoading(true);
      setIsRefreshPending(false);
      setError(null);

      try {
        if (!activeEntity?.id) {
          throw new Error("Authentication required");
        }
        const startedAt = performance.now();

        // Prepare preview data with active entity as issuer (if not already set)
        // Exclude 'number' as it's auto-generated by the render endpoint
        const { number: _number, ...invoiceDataWithoutNumber } = invoiceData as any;
        const previewData = normalizeDocumentPreviewDates({
          ...invoiceDataWithoutNumber,
          // Filter out unresolved tax_ids (race condition: form may add
          // { tax_id: undefined } before the tax dropdown auto-selects a value)
          items: filterUnresolvedTaxes(invoiceData.items),
          issuer: {
            name: activeEntity.name,
            address: activeEntity.address,
            address_2: activeEntity.address_2,
            post_code: activeEntity.post_code,
            city: activeEntity.city,
            state: activeEntity.state,
            country: activeEntity.country,
            tax_number: activeEntity.tax_number,
            ...invoiceData.issuer,
          },
        });
        const requestKey = JSON.stringify({
          documentType,
          template,
          qrOverrides,
          entityId: activeEntity.id,
          previewData,
        });
        if (lastRequestKeyRef.current === requestKey) {
          setIsLoading(false);
          setIsRefreshPending(false);
          emitLivePreviewDebug({
            stage: "deduped",
            documentType,
            itemCount: previewData.items?.length ?? 0,
          });
          return;
        }
        lastRequestKeyRef.current = requestKey;
        emitLivePreviewDebug({
          stage: "request_started",
          documentType,
          itemCount: previewData.items?.length ?? 0,
          template,
        });

        // Call the render API using the appropriate SDK method for the document type
        // Frontend preview requests intentionally avoid locale/language overrides.
        // Backend/entity defaults drive document formatting and default output language.
        const renderParams: Record<string, any> = { partial: "true" as const, template };
        if (qrOverrides?.upn_qr_enabled !== undefined) {
          renderParams.upn_qr_enabled = qrOverrides.upn_qr_enabled ? "true" : "false";
          if (qrOverrides.upn_qr_display_mode) {
            renderParams.upn_qr_display_mode = qrOverrides.upn_qr_display_mode;
          }
        }
        if (qrOverrides?.epc_qr_enabled !== undefined) {
          renderParams.epc_qr_enabled = qrOverrides.epc_qr_enabled ? "true" : "false";
        }
        const requestOpts = { entity_id: activeEntity.id, signal: abortController.signal };
        let html: string;
        switch (documentType) {
          case "estimate":
            html = await estimates.renderEstimatePreview(previewData as any, renderParams, requestOpts);
            break;
          case "credit_note":
            html = await creditNotes.renderCreditNotePreview(previewData as any, renderParams, requestOpts);
            break;
          case "advance_invoice":
            html = await advanceInvoices.renderAdvanceInvoicePreview(previewData as any, renderParams, requestOpts);
            break;
          case "delivery_note":
            html = await deliveryNotes.renderDeliveryNotePreview(previewData as any, renderParams, requestOpts);
            break;
          default:
            html = await invoices.renderInvoicePreview(previewData as any, renderParams, requestOpts);
            break;
        }

        setPreviewHtml(html);
        setError(null);
        emitLivePreviewDebug({
          stage: "request_succeeded",
          documentType,
          itemCount: previewData.items?.length ?? 0,
          elapsedMs: Number((performance.now() - startedAt).toFixed(1)),
        });
      } catch (err) {
        // Ignore abort errors (they're expected when user keeps typing)
        if (err instanceof Error && err.name === "AbortError") {
          emitLivePreviewDebug({
            stage: "request_aborted",
            documentType,
          });
          return;
        }

        // Ignore 422 validation errors - expected while user is still filling the form
        if (err instanceof Error && "status" in err && (err as any).status === 422) {
          emitLivePreviewDebug({
            stage: "request_validation_error",
            documentType,
            status: 422,
          });
          return;
        }

        setError(err instanceof Error ? err.message : "Failed to generate preview");
        setPreviewHtml("");
        lastRequestKeyRef.current = null;
        emitLivePreviewDebug({
          stage: "request_failed",
          documentType,
          message: err instanceof Error ? err.message : "Failed to generate preview",
        });
      } finally {
        // Only set loading to false if this request wasn't aborted
        if (!abortController.signal.aborted) {
          setIsLoading(false);
        }
      }
    },
    [
      activeEntity?.id,
      activeEntity?.address,
      activeEntity?.address_2,
      activeEntity?.country,
      activeEntity?.state,
      activeEntity?.tax_number,
      activeEntity?.post_code,
      activeEntity?.city,
      activeEntity?.name,
      template,
      documentType,
      qrOverrides,
      qrOverrides?.upn_qr_enabled,
      qrOverrides?.upn_qr_display_mode,
      qrOverrides?.epc_qr_enabled,
    ],
  );

  /**
   * Debounced preview fetch
   * Waits briefly after user stops typing before fetching
   */
  useEffect(() => {
    // Clear previous timeout
    if (debounceTimeoutRef.current) {
      clearTimeout(debounceTimeoutRef.current);
    }

    const hasItems = !!data.items && data.items.length > 0;
    const shouldFetchImmediately = eagerFirstPreview && hasItems && !hasDispatchedFirstPreviewRef.current;

    if (shouldFetchImmediately) {
      setIsRefreshPending(false);
      hasDispatchedFirstPreviewRef.current = true;
      fetchPreview(data);
    } else {
      setIsRefreshPending(hasItems);
      // Set new timeout
      debounceTimeoutRef.current = setTimeout(() => {
        setIsRefreshPending(false);
        hasDispatchedFirstPreviewRef.current = true;
        fetchPreview(data);
      }, LIVE_PREVIEW_DEBOUNCE_MS);
    }

    // Cleanup
    return () => {
      if (debounceTimeoutRef.current) {
        clearTimeout(debounceTimeoutRef.current);
      }
      setIsRefreshPending(false);
    };
  }, [data, eagerFirstPreview, fetchPreview]);

  /**
   * Cleanup on unmount
   */
  useEffect(() => {
    return () => {
      // Cancel any pending request
      if (abortControllerRef.current) {
        abortControllerRef.current.abort();
      }
      // Clear timeout
      if (debounceTimeoutRef.current) {
        clearTimeout(debounceTimeoutRef.current);
      }
      setIsRefreshPending(false);
      lastRequestKeyRef.current = null;
    };
  }, []);

  const showSkeleton = (!previewHtml && !error) || (isLoading && !previewHtml);
  const showRefreshBadge = !!previewHtml && (isRefreshPending || isLoading);

  return (
    <div
      ref={containerRef}
      className={cn("relative", className)}
      data-testid="live-preview"
      data-demo="marketing-demo-live-preview"
    >
      {/* Error state */}
      {error && !isLoading && (
        <div className="flex min-h-[200px] items-center justify-center rounded-lg border border-destructive/50 bg-destructive/10 p-8">
          <div className="text-center">
            <p className="font-semibold text-destructive">{t("Preview Error")}</p>
            <p className="text-muted-foreground text-sm">{error}</p>
          </div>
        </div>
      )}

      {/* Skeleton: shown on initial load and when loading without existing preview */}
      {showSkeleton && <DocumentPreviewSkeleton />}

      {/* Preview - Scoped HTML injection with A4 scaling */}
      {previewHtml && !error && (
        <div className="relative">
          {showRefreshBadge && (
            <div className="absolute top-4 right-4 z-20">
              <div className="inline-flex items-center gap-2 rounded-full border bg-background/95 px-3 py-1.5 text-muted-foreground text-xs shadow-sm">
                <Loader2 className={cn("size-3.5", (isRefreshPending || isLoading) && "animate-spin")} />
                <span>{isLoading ? t("Updating preview...") : t("Refreshing preview...")}</span>
              </div>
            </div>
          )}
          {isLoading && <div className="absolute inset-0 z-10 rounded-lg bg-background/35 backdrop-blur-[1.5px]" />}
          <div
            className={cn(isLoading && "opacity-75 transition-opacity duration-200")}
            data-demo="marketing-demo-totals-root"
          >
            <ScaledDocumentPreview htmlContent={previewHtml} scale={scale} A4_WIDTH_PX={A4_WIDTH_PX} />
          </div>
        </div>
      )}
    </div>
  );
}
