"use client";

import type { CreateInvoiceRequest } from "@spaceinvoices/js-sdk";
import { useCallback, useEffect, useRef, useState } from "react";
import { cn } from "@/ui/lib/utils";
import { useEntities } from "@/ui/providers/entities-context";
import { useSDK } from "@/ui/providers/sdk-provider";
import { DocumentPreviewSkeleton } from "../shared/document-preview-skeleton";
import { ScaledDocumentPreview } from "../shared/scaled-document-preview";
import { useA4Scaling } from "../shared/use-a4-scaling";
import type { DocumentTypes } from "../types";
import { filterUnresolvedTaxes } from "./prepare-preview-data";

export type PdfTemplateId = "modern" | "classic" | "condensed" | "minimal" | "fashion";

type LiveInvoicePreviewProps = {
  data: Partial<CreateInvoiceRequest>;
  currency?: string;
  template?: PdfTemplateId;
  className?: string;
  apiBaseUrl?: string;
  getAuthToken?: () => string | undefined;
  /** Locale for document rendering (e.g., "en-US", "sl-SI"). Uses user's UI language. */
  locale?: string;
  /** Fixed scale to use instead of dynamic scaling. Useful to prevent layout shifts. */
  fixedScale?: number;
  /** Translation function for UI strings */
  t?: (key: string) => string;
  /** Document type label for display (e.g., "Invoice", "Estimate") */
  documentTypeLabel?: string;
  /** Document type to determine which render endpoint to use */
  documentType?: DocumentTypes;
  /** QR settings overrides for preview (before saving) */
  qrOverrides?: {
    upn_qr_enabled?: boolean;
    upn_qr_display_mode?: "qr_only" | "full_slip";
    epc_qr_enabled?: boolean;
  };
};

/**
 * Live Invoice Preview Component
 *
 * Generates a real-time HTML preview of an invoice as the user fills out the form.
 * Uses debouncing to avoid excessive API calls and shows loading states.
 *
 * Features:
 * - Debounced API requests (500ms delay after user stops typing)
 * - Loading skeleton while fetching preview
 * - Error handling with fallback display
 * - Fully styled HTML with scoped CSS (prevents style leakage)
 */
export function LiveInvoicePreview({
  data,
  currency: _currency = "EUR",
  template,
  className,
  locale: _locale,
  fixedScale,
  t: tProp,
  documentTypeLabel: _documentTypeLabel,
  documentType = "invoice",
  qrOverrides,
}: LiveInvoicePreviewProps) {
  const t = tProp ?? ((key: string) => key);
  const [previewHtml, setPreviewHtml] = useState<string>("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const { activeEntity } = useEntities();
  const { sdk } = useSDK();
  const abortControllerRef = useRef<AbortController | null>(null);
  const debounceTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  const { containerRef, contentRef, scale: dynamicScale, contentHeight, A4_WIDTH_PX } = useA4Scaling(previewHtml);
  const scale = fixedScale ?? dynamicScale;

  /**
   * Fetch preview from API
   */
  const fetchPreview = useCallback(
    async (invoiceData: Partial<CreateInvoiceRequest>) => {
      // Don't fetch if no items exist (name can be empty for preview)
      if (!invoiceData.items || invoiceData.items.length === 0) {
        setPreviewHtml("");
        return;
      }

      // Cancel any pending request
      if (abortControllerRef.current) {
        abortControllerRef.current.abort();
      }

      // Create new abort controller for this request
      const abortController = new AbortController();
      abortControllerRef.current = abortController;

      setIsLoading(true);
      setError(null);

      try {
        if (!sdk || !activeEntity?.id) {
          throw new Error("Authentication required");
        }

        // Prepare preview data with active entity as issuer (if not already set)
        // Exclude 'number' as it's auto-generated by the render endpoint
        const { number: _number, ...invoiceDataWithoutNumber } = invoiceData as any;
        const previewData = {
          ...invoiceDataWithoutNumber,
          // Filter out unresolved tax_ids (race condition: form may add
          // { tax_id: undefined } before the tax dropdown auto-selects a value)
          items: filterUnresolvedTaxes(invoiceData.items),
          issuer: {
            name: activeEntity.name,
            address: activeEntity.address,
            address_2: activeEntity.address_2,
            post_code: activeEntity.post_code,
            city: activeEntity.city,
            state: activeEntity.state,
            country: activeEntity.country,
            tax_number: activeEntity.tax_number,
            ...invoiceData.issuer,
          },
        };

        // Call the render API using the appropriate SDK method for the document type
        // Don't send locale — let entity locale drive formatting (decimal separators, date format)
        const renderParams: Record<string, any> = { partial: "true" as const, template };
        if (qrOverrides?.upn_qr_enabled !== undefined) {
          renderParams.upn_qr_enabled = qrOverrides.upn_qr_enabled ? "true" : "false";
          if (qrOverrides.upn_qr_display_mode) {
            renderParams.upn_qr_display_mode = qrOverrides.upn_qr_display_mode;
          }
        }
        if (qrOverrides?.epc_qr_enabled !== undefined) {
          renderParams.epc_qr_enabled = qrOverrides.epc_qr_enabled ? "true" : "false";
        }
        const requestOpts = { entity_id: activeEntity.id };
        let html: string;
        switch (documentType) {
          case "estimate":
            html = await sdk.estimates.renderEstimatePreview(previewData as any, renderParams, requestOpts);
            break;
          case "credit_note":
            html = await sdk.creditNotes.renderCreditNotePreview(previewData as any, renderParams, requestOpts);
            break;
          case "advance_invoice":
            html = await sdk.advanceInvoices.renderAdvanceInvoicePreview(previewData as any, renderParams, requestOpts);
            break;
          case "delivery_note":
            html = await sdk.deliveryNotes.renderDeliveryNotePreview(previewData as any, renderParams, requestOpts);
            break;
          default:
            html = await sdk.invoices.renderInvoicePreview(previewData as any, renderParams, requestOpts);
            break;
        }

        setPreviewHtml(html);
        setError(null);
      } catch (err) {
        // Ignore abort errors (they're expected when user keeps typing)
        if (err instanceof Error && err.name === "AbortError") {
          return;
        }

        // Ignore 422 validation errors - expected while user is still filling the form
        if (err instanceof Error && "status" in err && (err as any).status === 422) {
          return;
        }

        setError(err instanceof Error ? err.message : "Failed to generate preview");
        setPreviewHtml("");
      } finally {
        // Only set loading to false if this request wasn't aborted
        if (!abortController.signal.aborted) {
          setIsLoading(false);
        }
      }
    },
    [
      activeEntity?.id,
      activeEntity?.address,
      activeEntity?.address_2,
      activeEntity?.country,
      activeEntity?.state,
      activeEntity?.tax_number,
      activeEntity?.post_code,
      activeEntity?.city,
      activeEntity?.name,
      template,
      sdk,
      documentType,
      qrOverrides?.upn_qr_enabled,
      qrOverrides?.upn_qr_display_mode,
      qrOverrides?.epc_qr_enabled,
    ],
  );

  /**
   * Debounced preview fetch
   * Waits 500ms after user stops typing before fetching
   */
  useEffect(() => {
    // Clear previous timeout
    if (debounceTimeoutRef.current) {
      clearTimeout(debounceTimeoutRef.current);
    }

    // Set new timeout
    debounceTimeoutRef.current = setTimeout(() => {
      fetchPreview(data);
    }, 500);

    // Cleanup
    return () => {
      if (debounceTimeoutRef.current) {
        clearTimeout(debounceTimeoutRef.current);
      }
    };
  }, [data, fetchPreview]);

  /**
   * Cleanup on unmount
   */
  useEffect(() => {
    return () => {
      // Cancel any pending request
      if (abortControllerRef.current) {
        abortControllerRef.current.abort();
      }
      // Clear timeout
      if (debounceTimeoutRef.current) {
        clearTimeout(debounceTimeoutRef.current);
      }
    };
  }, []);

  const showSkeleton = (!previewHtml && !error) || (isLoading && !previewHtml);

  return (
    <div ref={containerRef} className={cn("relative", className)}>
      {/* Error state */}
      {error && !isLoading && (
        <div className="flex min-h-[200px] items-center justify-center rounded-lg border border-destructive/50 bg-destructive/10 p-8">
          <div className="text-center">
            <p className="font-semibold text-destructive">{t("Preview Error")}</p>
            <p className="text-muted-foreground text-sm">{error}</p>
          </div>
        </div>
      )}

      {/* Skeleton: shown on initial load and when loading without existing preview */}
      {showSkeleton && <DocumentPreviewSkeleton />}

      {/* Preview - Scoped HTML injection with A4 scaling */}
      {previewHtml && !error && (
        <div className={cn(isLoading && "opacity-50 transition-opacity duration-200")}>
          <ScaledDocumentPreview
            htmlContent={previewHtml}
            scale={scale}
            contentHeight={contentHeight}
            A4_WIDTH_PX={A4_WIDTH_PX}
            contentRef={contentRef}
          />
        </div>
      )}
    </div>
  );
}
