type CustomerData = {
  name?: string | null;
  address?: string | null;
  address_2?: string | null;
  post_code?: string | null;
  city?: string | null;
  state?: string | null;
  country?: string | null;
  tax_number?: string | null;
  is_end_consumer?: boolean | null;
  save_customer?: boolean;
};

type BaseDocumentValues = {
  number?: string;
  date?: string;
  customer_id?: string | null;
  customer?: CustomerData | null;

  items?: any[];
  currency_code?: string;
};

/** Map of item index to gross price mode */
type PriceModesMap = Record<number, boolean>;

type PrepareDocumentOptions = {
  /** Original customer data for comparison (to detect modifications) */
  originalCustomer: CustomerData | null;
  /** Whether the customer form was shown to the user */
  wasCustomerFormShown?: boolean;
  /** For invoices/credit notes: whether to mark as paid */
  markAsPaid?: boolean;
  /** For invoices/credit notes: payment types when markAsPaid is true */
  paymentTypes?: string[];
  /** Structured payments when amounts were already normalized by the form layer */
  payments?: Array<{ type: string; amount?: number }>;
  /** Document type for specific date handling */
  documentType: "invoice" | "estimate" | "credit_note" | "advance_invoice" | "delivery_note";
  /** Secondary date field value (date_due for invoices, date_valid_till for estimates) */
  secondaryDate?: string;
  /** Map of item index to gross price mode (collected from component state) */
  priceModes?: PriceModesMap;
  /** Whether to save as draft (skips numbering and fiscalization) */
  isDraft?: boolean;
};

/**
 * Prepares document form data for API submission.
 * Handles customer data transformation and payment data for all document types.
 *
 * This is a shared utility for invoices, estimates, and credit notes.
 *
 * @example
 * ```ts
 * // For invoice
 * const payload = prepareDocumentSubmission(values, {
 *   originalCustomer,
 *   wasCustomerFormShown: showCustomerForm,
 *   markAsPaid: values.markAsPaid,
 *   paymentType: values.paymentType,
 *   documentType: "invoice",
 *   secondaryDate: values.date_due,
 * });
 *
 * // For estimate
 * const payload = prepareDocumentSubmission(values, {
 *   originalCustomer,
 *   documentType: "estimate",
 *   secondaryDate: values.date_valid_till,
 * });
 * ```
 */
export function prepareDocumentSubmission<T extends BaseDocumentValues>(
  values: T,
  options: PrepareDocumentOptions,
): any {
  const nextValues: any = {
    ...values,
    customer: values.customer ? { ...values.customer } : values.customer,
    items: values.items
      ? values.items.map((item: any) => ({ ...item, taxes: item?.taxes ? [...item.taxes] : item?.taxes }))
      : values.items,
  };

  // Document numbers are always auto-generated by the server
  // Remove number from payload (even if form provides a preview value)

  // Handle customer logic
  if (nextValues.customer_id && nextValues.customer) {
    // If customer form was not shown, remove customer data (keep only customer_id)
    if (options.wasCustomerFormShown === false) {
      delete nextValues.customer;
    } else {
      // Existing customer loaded - check if data was actually modified
      const customerChanged =
        options.originalCustomer && JSON.stringify(nextValues.customer) !== JSON.stringify(options.originalCustomer);

      if (!customerChanged) {
        // No changes - send only customer_id
        delete nextValues.customer;
      } else {
        // Changes detected - clean null/empty values and send with save_customer flag
        const cleanedCustomer: any = { save_customer: true };
        for (const [key, value] of Object.entries(nextValues.customer)) {
          if (key !== "save_customer" && value !== "" && value !== null && value !== undefined) {
            cleanedCustomer[key] = value;
          }
        }
        nextValues.customer = cleanedCustomer;
      }
    }
  } else if (nextValues.customer) {
    // New inline customer - clean null/empty values and add save flag
    const cleanedCustomer: any = { save_customer: true };
    let hasAnyValue = false;

    for (const [key, value] of Object.entries(nextValues.customer)) {
      if (key !== "save_customer" && value !== "" && value !== null && value !== undefined) {
        cleanedCustomer[key] = value;
        hasAnyValue = true;
      }
    }

    if (!hasAnyValue) {
      delete nextValues.customer;
    } else {
      nextValues.customer = cleanedCustomer;
    }
  }

  // Clean up customer_id if empty
  if (!nextValues.customer_id) {
    delete nextValues.customer_id;
  }

  // Clean up taxes and handle gross price transformation
  if (nextValues.items) {
    const priceModes = options.priceModes ?? {};
    nextValues.items = nextValues.items.map((item: any, index: number) => {
      // Separator items — pass through with only type, name, description
      if (item.type === "separator") {
        return {
          type: "separator",
          name: item.name,
          description: item.description || undefined,
        };
      }

      const { price, ...rest } = item;

      // Transform price based on price mode (from component state, not form)
      const isGrossPrice = priceModes[index] ?? false;
      const priceFields = isGrossPrice ? { gross_price: price } : { price };

      return {
        ...rest,
        ...priceFields,
        taxes: item.taxes
          ?.map((tax: any) => {
            if (tax.tax_id) {
              // Preserve PT exemption metadata while still allowing the API to resolve the tax rate by tax_id.
              return {
                tax_id: tax.tax_id,
                ...(tax.pt_exemption_code ? { pt_exemption_code: tax.pt_exemption_code } : {}),
                ...(tax.pt_exemption_reason ? { pt_exemption_reason: tax.pt_exemption_reason } : {}),
              };
            }
            return tax;
          })
          // Filter out empty placeholder taxes (UI adds { tax_id: undefined } for the dropdown)
          .filter((tax: any) => tax.tax_id || tax.rate !== undefined || tax.classification),
      };
    });
  }

  // Build payload with date conversions
  // Destructure to exclude fields we handle explicitly (number is always server-generated)
  const { number: _number, note, payment_terms, reference, signature, pt: _pt, ...restValues } = nextValues as any;
  const payload: any = {
    ...restValues,
    ...(note?.trim() && { note: note.trim() }),
    ...(reference?.trim() && { reference: reference.trim() }),
    // Advance invoices don't have payment terms - they are documents requesting payment
    ...(options.documentType !== "advance_invoice" && payment_terms?.trim() && { payment_terms: payment_terms.trim() }),
    ...(signature?.trim() && { signature: signature.trim() }),
    date: nextValues.date ? new Date(nextValues.date) : undefined,
  };

  // Add secondary date field based on document type
  if ((options.documentType === "invoice" || options.documentType === "advance_invoice") && options.secondaryDate) {
    payload.date_due = new Date(options.secondaryDate);
  } else if (options.documentType === "estimate" && options.secondaryDate) {
    payload.date_valid_till = new Date(options.secondaryDate);
  }
  // Credit notes don't have a secondary date field

  // Add service date fields for invoices and credit notes
  if (options.documentType === "invoice" || options.documentType === "credit_note") {
    const v = nextValues as any;
    if (v.date_service) {
      payload.date_service = new Date(v.date_service);
    }
    if (v.date_service_to) {
      payload.date_service_to = new Date(v.date_service_to);
    }
  }

  // Handle markAsPaid for invoices and credit notes
  if (options.documentType !== "estimate" && options.markAsPaid) {
    const serializedPayments =
      options.payments?.map((payment) => ({
        ...payment,
        date: payload.date ?? undefined,
      })) ??
      options.paymentTypes?.map((type: string) => ({
        type,
        date: payload.date ?? undefined,
      })) ??
      [];

    if (serializedPayments.length > 0) {
      payload.payments = serializedPayments;
    }
  }

  // Remove UI-only fields from payload
  delete payload.markAsPaid;
  delete payload.paymentTypes;

  // Add draft flag if requested
  if (options.isDraft) {
    payload.is_draft = true;
  }

  return payload;
}
